// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc_server.proto

/*
Package qlik is a generated protocol buffer package.

It is generated from these files:
	grpc_server.proto

It has these top-level messages:
	ConnectionInfo
	GenericCommand
	GenericCommandResponse
	SessionInfo
	DataInfo
	GetDataOptions
	Dual
	Row
	BundledRows
	BundledRows2
	Column
	BundledRows3
	FieldInfo
	ResultSpec
	ResultChunk
*/
package qlik

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FieldType int32

const (
	FieldType_UNKNOWN   FieldType = 0
	FieldType_ASCII     FieldType = 1
	FieldType_REAL      FieldType = 2
	FieldType_DATE      FieldType = 3
	FieldType_TIME      FieldType = 4
	FieldType_TIMESTAMP FieldType = 5
	FieldType_INTERVAL  FieldType = 6
	FieldType_INTEGER   FieldType = 7
	FieldType_FIX       FieldType = 8
	FieldType_MONEY     FieldType = 9
)

var FieldType_name = map[int32]string{
	0: "UNKNOWN",
	1: "ASCII",
	2: "REAL",
	3: "DATE",
	4: "TIME",
	5: "TIMESTAMP",
	6: "INTERVAL",
	7: "INTEGER",
	8: "FIX",
	9: "MONEY",
}
var FieldType_value = map[string]int32{
	"UNKNOWN":   0,
	"ASCII":     1,
	"REAL":      2,
	"DATE":      3,
	"TIME":      4,
	"TIMESTAMP": 5,
	"INTERVAL":  6,
	"INTEGER":   7,
	"FIX":       8,
	"MONEY":     9,
}

func (x FieldType) String() string {
	return proto.EnumName(FieldType_name, int32(x))
}
func (FieldType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ConnectionInfo struct {
	ConnectionString string `protobuf:"bytes,1,opt,name=connectionString" json:"connectionString,omitempty"`
	User             string `protobuf:"bytes,2,opt,name=user" json:"user,omitempty"`
	Password         string `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
}

func (m *ConnectionInfo) Reset()                    { *m = ConnectionInfo{} }
func (m *ConnectionInfo) String() string            { return proto.CompactTextString(m) }
func (*ConnectionInfo) ProtoMessage()               {}
func (*ConnectionInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ConnectionInfo) GetConnectionString() string {
	if m != nil {
		return m.ConnectionString
	}
	return ""
}

func (m *ConnectionInfo) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *ConnectionInfo) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type GenericCommand struct {
	Command    string          `protobuf:"bytes,1,opt,name=command" json:"command,omitempty"`
	Method     string          `protobuf:"bytes,2,opt,name=method" json:"method,omitempty"`
	Parameters []string        `protobuf:"bytes,3,rep,name=parameters" json:"parameters,omitempty"`
	Connection *ConnectionInfo `protobuf:"bytes,4,opt,name=connection" json:"connection,omitempty"`
}

func (m *GenericCommand) Reset()                    { *m = GenericCommand{} }
func (m *GenericCommand) String() string            { return proto.CompactTextString(m) }
func (*GenericCommand) ProtoMessage()               {}
func (*GenericCommand) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GenericCommand) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *GenericCommand) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *GenericCommand) GetParameters() []string {
	if m != nil {
		return m.Parameters
	}
	return nil
}

func (m *GenericCommand) GetConnection() *ConnectionInfo {
	if m != nil {
		return m.Connection
	}
	return nil
}

type GenericCommandResponse struct {
	Data string `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
}

func (m *GenericCommandResponse) Reset()                    { *m = GenericCommandResponse{} }
func (m *GenericCommandResponse) String() string            { return proto.CompactTextString(m) }
func (*GenericCommandResponse) ProtoMessage()               {}
func (*GenericCommandResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GenericCommandResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type SessionInfo struct {
	User      string `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	SessionId string `protobuf:"bytes,2,opt,name=sessionId" json:"sessionId,omitempty"`
	DocId     string `protobuf:"bytes,3,opt,name=docId" json:"docId,omitempty"`
}

func (m *SessionInfo) Reset()                    { *m = SessionInfo{} }
func (m *SessionInfo) String() string            { return proto.CompactTextString(m) }
func (*SessionInfo) ProtoMessage()               {}
func (*SessionInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *SessionInfo) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *SessionInfo) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *SessionInfo) GetDocId() string {
	if m != nil {
		return m.DocId
	}
	return ""
}

type DataInfo struct {
	Statement           string `protobuf:"bytes,1,opt,name=statement" json:"statement,omitempty"`
	StatementParameters string `protobuf:"bytes,2,opt,name=statementParameters" json:"statementParameters,omitempty"`
}

func (m *DataInfo) Reset()                    { *m = DataInfo{} }
func (m *DataInfo) String() string            { return proto.CompactTextString(m) }
func (*DataInfo) ProtoMessage()               {}
func (*DataInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *DataInfo) GetStatement() string {
	if m != nil {
		return m.Statement
	}
	return ""
}

func (m *DataInfo) GetStatementParameters() string {
	if m != nil {
		return m.StatementParameters
	}
	return ""
}

type GetDataOptions struct {
	Connection  *ConnectionInfo `protobuf:"bytes,1,opt,name=connection" json:"connection,omitempty"`
	SessionInfo *SessionInfo    `protobuf:"bytes,2,opt,name=sessionInfo" json:"sessionInfo,omitempty"`
	Parameters  *DataInfo       `protobuf:"bytes,3,opt,name=parameters" json:"parameters,omitempty"`
}

func (m *GetDataOptions) Reset()                    { *m = GetDataOptions{} }
func (m *GetDataOptions) String() string            { return proto.CompactTextString(m) }
func (*GetDataOptions) ProtoMessage()               {}
func (*GetDataOptions) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *GetDataOptions) GetConnection() *ConnectionInfo {
	if m != nil {
		return m.Connection
	}
	return nil
}

func (m *GetDataOptions) GetSessionInfo() *SessionInfo {
	if m != nil {
		return m.SessionInfo
	}
	return nil
}

func (m *GetDataOptions) GetParameters() *DataInfo {
	if m != nil {
		return m.Parameters
	}
	return nil
}

type Dual struct {
	NumData   float64 `protobuf:"fixed64,1,opt,name=numData" json:"numData,omitempty"`
	StrData   string  `protobuf:"bytes,2,opt,name=strData" json:"strData,omitempty"`
	StrIsNull bool    `protobuf:"varint,3,opt,name=strIsNull" json:"strIsNull,omitempty"`
}

func (m *Dual) Reset()                    { *m = Dual{} }
func (m *Dual) String() string            { return proto.CompactTextString(m) }
func (*Dual) ProtoMessage()               {}
func (*Dual) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Dual) GetNumData() float64 {
	if m != nil {
		return m.NumData
	}
	return 0
}

func (m *Dual) GetStrData() string {
	if m != nil {
		return m.StrData
	}
	return ""
}

func (m *Dual) GetStrIsNull() bool {
	if m != nil {
		return m.StrIsNull
	}
	return false
}

type Row struct {
	Duals []*Dual `protobuf:"bytes,1,rep,name=duals" json:"duals,omitempty"`
}

func (m *Row) Reset()                    { *m = Row{} }
func (m *Row) String() string            { return proto.CompactTextString(m) }
func (*Row) ProtoMessage()               {}
func (*Row) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Row) GetDuals() []*Dual {
	if m != nil {
		return m.Duals
	}
	return nil
}

type BundledRows struct {
	Rows []*Row `protobuf:"bytes,1,rep,name=rows" json:"rows,omitempty"`
}

func (m *BundledRows) Reset()                    { *m = BundledRows{} }
func (m *BundledRows) String() string            { return proto.CompactTextString(m) }
func (*BundledRows) ProtoMessage()               {}
func (*BundledRows) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *BundledRows) GetRows() []*Row {
	if m != nil {
		return m.Rows
	}
	return nil
}

type BundledRows2 struct {
	RowCount    int64     `protobuf:"varint,1,opt,name=rowCount" json:"rowCount,omitempty"`
	ColumnCount int64     `protobuf:"varint,2,opt,name=columnCount" json:"columnCount,omitempty"`
	Strings     []string  `protobuf:"bytes,3,rep,name=strings" json:"strings,omitempty"`
	Numerics    []float64 `protobuf:"fixed64,4,rep,packed,name=numerics" json:"numerics,omitempty"`
	StrIsNulls  []bool    `protobuf:"varint,5,rep,packed,name=strIsNulls" json:"strIsNulls,omitempty"`
	RawData     []byte    `protobuf:"bytes,6,opt,name=rawData,proto3" json:"rawData,omitempty"`
}

func (m *BundledRows2) Reset()                    { *m = BundledRows2{} }
func (m *BundledRows2) String() string            { return proto.CompactTextString(m) }
func (*BundledRows2) ProtoMessage()               {}
func (*BundledRows2) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *BundledRows2) GetRowCount() int64 {
	if m != nil {
		return m.RowCount
	}
	return 0
}

func (m *BundledRows2) GetColumnCount() int64 {
	if m != nil {
		return m.ColumnCount
	}
	return 0
}

func (m *BundledRows2) GetStrings() []string {
	if m != nil {
		return m.Strings
	}
	return nil
}

func (m *BundledRows2) GetNumerics() []float64 {
	if m != nil {
		return m.Numerics
	}
	return nil
}

func (m *BundledRows2) GetStrIsNulls() []bool {
	if m != nil {
		return m.StrIsNulls
	}
	return nil
}

func (m *BundledRows2) GetRawData() []byte {
	if m != nil {
		return m.RawData
	}
	return nil
}

type Column struct {
	Strings    []string  `protobuf:"bytes,3,rep,name=strings" json:"strings,omitempty"`
	Numerics   []float64 `protobuf:"fixed64,4,rep,packed,name=numerics" json:"numerics,omitempty"`
	StrIsNulls []bool    `protobuf:"varint,5,rep,packed,name=strIsNulls" json:"strIsNulls,omitempty"`
}

func (m *Column) Reset()                    { *m = Column{} }
func (m *Column) String() string            { return proto.CompactTextString(m) }
func (*Column) ProtoMessage()               {}
func (*Column) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *Column) GetStrings() []string {
	if m != nil {
		return m.Strings
	}
	return nil
}

func (m *Column) GetNumerics() []float64 {
	if m != nil {
		return m.Numerics
	}
	return nil
}

func (m *Column) GetStrIsNulls() []bool {
	if m != nil {
		return m.StrIsNulls
	}
	return nil
}

type BundledRows3 struct {
	RowCount int64     `protobuf:"varint,1,opt,name=rowCount" json:"rowCount,omitempty"`
	Column   []*Column `protobuf:"bytes,3,rep,name=column" json:"column,omitempty"`
}

func (m *BundledRows3) Reset()                    { *m = BundledRows3{} }
func (m *BundledRows3) String() string            { return proto.CompactTextString(m) }
func (*BundledRows3) ProtoMessage()               {}
func (*BundledRows3) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *BundledRows3) GetRowCount() int64 {
	if m != nil {
		return m.RowCount
	}
	return 0
}

func (m *BundledRows3) GetColumn() []*Column {
	if m != nil {
		return m.Column
	}
	return nil
}

type FieldInfo struct {
	Name string    `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Type FieldType `protobuf:"varint,2,opt,name=type,enum=qlik.FieldType" json:"type,omitempty"`
}

func (m *FieldInfo) Reset()                    { *m = FieldInfo{} }
func (m *FieldInfo) String() string            { return proto.CompactTextString(m) }
func (*FieldInfo) ProtoMessage()               {}
func (*FieldInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *FieldInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FieldInfo) GetType() FieldType {
	if m != nil {
		return m.Type
	}
	return FieldType_UNKNOWN
}

type ResultSpec struct {
	FieldInfo []*FieldInfo `protobuf:"bytes,1,rep,name=fieldInfo" json:"fieldInfo,omitempty"`
	TableName string       `protobuf:"bytes,2,opt,name=tableName" json:"tableName,omitempty"`
}

func (m *ResultSpec) Reset()                    { *m = ResultSpec{} }
func (m *ResultSpec) String() string            { return proto.CompactTextString(m) }
func (*ResultSpec) ProtoMessage()               {}
func (*ResultSpec) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *ResultSpec) GetFieldInfo() []*FieldInfo {
	if m != nil {
		return m.FieldInfo
	}
	return nil
}

func (m *ResultSpec) GetTableName() string {
	if m != nil {
		return m.TableName
	}
	return ""
}

type ResultChunk struct {
	ResultSpec    *ResultSpec   `protobuf:"bytes,1,opt,name=resultSpec" json:"resultSpec,omitempty"`
	RowsOfDuals   *BundledRows  `protobuf:"bytes,2,opt,name=rowsOfDuals" json:"rowsOfDuals,omitempty"`
	CellsByRow    *BundledRows2 `protobuf:"bytes,3,opt,name=cellsByRow" json:"cellsByRow,omitempty"`
	CellsByColumn *BundledRows3 `protobuf:"bytes,4,opt,name=cellsByColumn" json:"cellsByColumn,omitempty"`
}

func (m *ResultChunk) Reset()                    { *m = ResultChunk{} }
func (m *ResultChunk) String() string            { return proto.CompactTextString(m) }
func (*ResultChunk) ProtoMessage()               {}
func (*ResultChunk) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *ResultChunk) GetResultSpec() *ResultSpec {
	if m != nil {
		return m.ResultSpec
	}
	return nil
}

func (m *ResultChunk) GetRowsOfDuals() *BundledRows {
	if m != nil {
		return m.RowsOfDuals
	}
	return nil
}

func (m *ResultChunk) GetCellsByRow() *BundledRows2 {
	if m != nil {
		return m.CellsByRow
	}
	return nil
}

func (m *ResultChunk) GetCellsByColumn() *BundledRows3 {
	if m != nil {
		return m.CellsByColumn
	}
	return nil
}

func init() {
	proto.RegisterType((*ConnectionInfo)(nil), "qlik.ConnectionInfo")
	proto.RegisterType((*GenericCommand)(nil), "qlik.GenericCommand")
	proto.RegisterType((*GenericCommandResponse)(nil), "qlik.GenericCommandResponse")
	proto.RegisterType((*SessionInfo)(nil), "qlik.SessionInfo")
	proto.RegisterType((*DataInfo)(nil), "qlik.DataInfo")
	proto.RegisterType((*GetDataOptions)(nil), "qlik.GetDataOptions")
	proto.RegisterType((*Dual)(nil), "qlik.Dual")
	proto.RegisterType((*Row)(nil), "qlik.Row")
	proto.RegisterType((*BundledRows)(nil), "qlik.BundledRows")
	proto.RegisterType((*BundledRows2)(nil), "qlik.BundledRows2")
	proto.RegisterType((*Column)(nil), "qlik.Column")
	proto.RegisterType((*BundledRows3)(nil), "qlik.BundledRows3")
	proto.RegisterType((*FieldInfo)(nil), "qlik.FieldInfo")
	proto.RegisterType((*ResultSpec)(nil), "qlik.ResultSpec")
	proto.RegisterType((*ResultChunk)(nil), "qlik.ResultChunk")
	proto.RegisterEnum("qlik.FieldType", FieldType_name, FieldType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Connector service

type ConnectorClient interface {
	GetData2(ctx context.Context, in *GetDataOptions, opts ...grpc.CallOption) (Connector_GetData2Client, error)
}

type connectorClient struct {
	cc *grpc.ClientConn
}

func NewConnectorClient(cc *grpc.ClientConn) ConnectorClient {
	return &connectorClient{cc}
}

func (c *connectorClient) GetData2(ctx context.Context, in *GetDataOptions, opts ...grpc.CallOption) (Connector_GetData2Client, error) {
	stream, err := grpc.NewClientStream(ctx, &_Connector_serviceDesc.Streams[0], c.cc, "/qlik.Connector/GetData2", opts...)
	if err != nil {
		return nil, err
	}
	x := &connectorGetData2Client{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Connector_GetData2Client interface {
	Recv() (*ResultChunk, error)
	grpc.ClientStream
}

type connectorGetData2Client struct {
	grpc.ClientStream
}

func (x *connectorGetData2Client) Recv() (*ResultChunk, error) {
	m := new(ResultChunk)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Connector service

type ConnectorServer interface {
	GetData2(*GetDataOptions, Connector_GetData2Server) error
}

func RegisterConnectorServer(s *grpc.Server, srv ConnectorServer) {
	s.RegisterService(&_Connector_serviceDesc, srv)
}

func _Connector_GetData2_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetDataOptions)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ConnectorServer).GetData2(m, &connectorGetData2Server{stream})
}

type Connector_GetData2Server interface {
	Send(*ResultChunk) error
	grpc.ServerStream
}

type connectorGetData2Server struct {
	grpc.ServerStream
}

func (x *connectorGetData2Server) Send(m *ResultChunk) error {
	return x.ServerStream.SendMsg(m)
}

var _Connector_serviceDesc = grpc.ServiceDesc{
	ServiceName: "qlik.Connector",
	HandlerType: (*ConnectorServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetData2",
			Handler:       _Connector_GetData2_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "grpc_server.proto",
}

func init() { proto.RegisterFile("grpc_server.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 854 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0xdd, 0x6e, 0xdc, 0x44,
	0x14, 0xae, 0x63, 0xef, 0xc6, 0x3e, 0x4e, 0x83, 0x33, 0x54, 0x91, 0x55, 0x01, 0xb2, 0x0c, 0x12,
	0xab, 0xaa, 0x44, 0x91, 0x83, 0x04, 0xb7, 0x9b, 0xdd, 0x6d, 0xb4, 0xa2, 0xd9, 0x84, 0xd9, 0x2d,
	0xb4, 0x5c, 0x80, 0x5c, 0x7b, 0x92, 0xae, 0x62, 0xcf, 0x98, 0x19, 0x9b, 0x55, 0xae, 0x78, 0x0d,
	0xde, 0x81, 0x57, 0xe0, 0x69, 0x78, 0x12, 0x34, 0xe3, 0x19, 0xaf, 0xb7, 0x41, 0x88, 0x9b, 0xde,
	0x9d, 0xf3, 0x9d, 0xbf, 0x39, 0xdf, 0x9c, 0x33, 0x03, 0x47, 0xb7, 0xbc, 0xca, 0x7e, 0x11, 0x84,
	0xff, 0x46, 0xf8, 0x49, 0xc5, 0x59, 0xcd, 0x90, 0xf3, 0x6b, 0xb1, 0xbe, 0x8b, 0x0b, 0x38, 0x9c,
	0x30, 0x4a, 0x49, 0x56, 0xaf, 0x19, 0x9d, 0xd3, 0x1b, 0x86, 0x9e, 0x41, 0x90, 0x75, 0xc8, 0xb2,
	0xe6, 0x6b, 0x7a, 0x1b, 0x5a, 0x91, 0x35, 0xf2, 0xf0, 0x03, 0x1c, 0x21, 0x70, 0x1a, 0x41, 0x78,
	0xb8, 0xa7, 0xec, 0x4a, 0x46, 0x4f, 0xc1, 0xad, 0x52, 0x21, 0x36, 0x8c, 0xe7, 0xa1, 0xad, 0xf0,
	0x4e, 0x8f, 0xff, 0xb0, 0xe0, 0xf0, 0x82, 0x50, 0xc2, 0xd7, 0xd9, 0x84, 0x95, 0x65, 0x4a, 0x73,
	0x14, 0xc2, 0x7e, 0xd6, 0x8a, 0xba, 0x8a, 0x51, 0xd1, 0x31, 0x0c, 0x4b, 0x52, 0xbf, 0x63, 0xb9,
	0x4e, 0xaf, 0x35, 0xf4, 0x19, 0x40, 0x95, 0xf2, 0xb4, 0x24, 0x35, 0xe1, 0x22, 0xb4, 0x23, 0x7b,
	0xe4, 0xe1, 0x1e, 0x82, 0xbe, 0x06, 0xd8, 0x1e, 0x34, 0x74, 0x22, 0x6b, 0xe4, 0x27, 0x4f, 0x4e,
	0x64, 0xb7, 0x27, 0xbb, 0xad, 0xe2, 0x9e, 0x5f, 0xfc, 0x1c, 0x8e, 0x77, 0x4f, 0x86, 0x89, 0xa8,
	0x18, 0x15, 0x44, 0x36, 0x99, 0xa7, 0x75, 0xaa, 0x8f, 0xa7, 0xe4, 0xf8, 0x15, 0xf8, 0x4b, 0x22,
	0x84, 0xe1, 0xcc, 0xf0, 0x60, 0xf5, 0x78, 0xf8, 0x04, 0x3c, 0xa1, 0x5d, 0x4c, 0x07, 0x5b, 0x00,
	0x3d, 0x81, 0x41, 0xce, 0xb2, 0xb9, 0xa1, 0xa8, 0x55, 0xe2, 0x9f, 0xc0, 0x9d, 0xa6, 0x75, 0xaa,
	0x72, 0xca, 0xf8, 0x3a, 0xad, 0x49, 0x49, 0x68, 0xad, 0x13, 0x6f, 0x01, 0x74, 0x0a, 0x1f, 0x77,
	0xca, 0xf5, 0x96, 0x8d, 0xb6, 0xce, 0xbf, 0x99, 0xe2, 0x3f, 0x15, 0xf7, 0xb5, 0xcc, 0x7f, 0x55,
	0xc9, 0x96, 0xdf, 0x67, 0xca, 0xfa, 0x7f, 0x4c, 0xa1, 0x33, 0xf0, 0xc5, 0xb6, 0x77, 0x55, 0xd2,
	0x4f, 0x8e, 0xda, 0xb0, 0x1e, 0x29, 0xb8, 0xef, 0x85, 0x4e, 0xde, 0xbb, 0x34, 0x19, 0x73, 0xd8,
	0xc6, 0x98, 0x8e, 0xfb, 0x97, 0x18, 0xbf, 0x06, 0x67, 0xda, 0xa4, 0x85, 0x1c, 0x0f, 0xda, 0x94,
	0x53, 0xc3, 0xbf, 0x85, 0x8d, 0x2a, 0x2d, 0xa2, 0xe6, 0xca, 0xd2, 0x76, 0x6d, 0xd4, 0x96, 0x39,
	0x3e, 0x17, 0x8b, 0xa6, 0x28, 0x54, 0x29, 0x17, 0x6f, 0x81, 0xf8, 0x4b, 0xb0, 0x31, 0xdb, 0xa0,
	0x08, 0x06, 0x79, 0x93, 0x16, 0x22, 0xb4, 0x22, 0x7b, 0xe4, 0x27, 0xa0, 0xcf, 0xd2, 0xa4, 0x05,
	0x6e, 0x0d, 0xf1, 0x73, 0xf0, 0xcf, 0x1b, 0x9a, 0x17, 0x24, 0xc7, 0x6c, 0x23, 0xd0, 0xa7, 0xe0,
	0x70, 0xb6, 0x31, 0xfe, 0x5e, 0xeb, 0x8f, 0xd9, 0x06, 0x2b, 0x38, 0xfe, 0xcb, 0x82, 0x83, 0x9e,
	0x7b, 0x22, 0xf7, 0x80, 0xb3, 0xcd, 0x84, 0x35, 0xfa, 0xfa, 0x6c, 0xdc, 0xe9, 0x28, 0x02, 0x3f,
	0x63, 0x45, 0x53, 0xd2, 0xd6, 0xbc, 0xa7, 0xcc, 0x7d, 0x48, 0x77, 0xb7, 0xa6, 0xb7, 0x66, 0xc2,
	0x8d, 0x2a, 0xf3, 0xd2, 0xa6, 0x94, 0x83, 0x2a, 0x42, 0x27, 0xb2, 0x47, 0x16, 0xee, 0x74, 0xb9,
	0x1a, 0x5d, 0xa3, 0x22, 0x1c, 0x44, 0xf6, 0xc8, 0xc5, 0x3d, 0x44, 0x66, 0xe5, 0xe9, 0x46, 0x71,
	0x36, 0x8c, 0xac, 0xd1, 0x01, 0x36, 0x6a, 0xfc, 0x33, 0x0c, 0x27, 0xaa, 0xfc, 0x87, 0xa9, 0x1c,
	0x5f, 0xef, 0xb0, 0x73, 0xf6, 0x9f, 0xec, 0x7c, 0x01, 0xc3, 0x96, 0x0a, 0x75, 0x00, 0x3f, 0x39,
	0x30, 0x23, 0x29, 0x31, 0xac, 0x6d, 0xf1, 0x14, 0xbc, 0x17, 0x6b, 0x52, 0xe4, 0x66, 0x01, 0x69,
	0x5a, 0x12, 0xb3, 0x80, 0x52, 0x46, 0x9f, 0x83, 0x53, 0xdf, 0x57, 0x44, 0xb1, 0x7b, 0x98, 0x7c,
	0xd4, 0x26, 0x51, 0x21, 0xab, 0xfb, 0x8a, 0x60, 0x65, 0x8c, 0xdf, 0x00, 0x60, 0x22, 0x9a, 0xa2,
	0x5e, 0x56, 0x24, 0x43, 0x5f, 0x81, 0x77, 0x63, 0x72, 0xea, 0x8b, 0xee, 0xc7, 0xa9, 0x29, 0xdd,
	0x7a, 0xc8, 0x41, 0xab, 0xd3, 0xb7, 0x05, 0x59, 0xc8, 0xd2, 0x7a, 0xc5, 0x3b, 0x20, 0xfe, 0xdb,
	0x02, 0xbf, 0xcd, 0x3d, 0x79, 0xd7, 0xd0, 0x3b, 0x74, 0x0a, 0xc0, 0xbb, 0x52, 0x7a, 0xdb, 0x02,
	0x3d, 0x46, 0x1d, 0x8e, 0x7b, 0x3e, 0x72, 0xd3, 0xe4, 0x6c, 0x5d, 0xdd, 0x4c, 0xd5, 0xa4, 0xee,
	0x6c, 0x5a, 0x8f, 0x4d, 0xdc, 0xf7, 0x42, 0x09, 0x40, 0x46, 0x8a, 0x42, 0x9c, 0xdf, 0x63, 0xb6,
	0xd1, 0x9b, 0x86, 0x1e, 0xc4, 0x24, 0xb8, 0xe7, 0x85, 0xbe, 0x85, 0xc7, 0x5a, 0x6b, 0x49, 0xd6,
	0xaf, 0xe6, 0xc3, 0xb0, 0x33, 0xbc, 0xeb, 0xf8, 0xec, 0x77, 0x7d, 0x0b, 0x92, 0x52, 0xe4, 0xc3,
	0xfe, 0xab, 0xc5, 0x77, 0x8b, 0xab, 0x1f, 0x17, 0xc1, 0x23, 0xe4, 0xc1, 0x60, 0xbc, 0x9c, 0xcc,
	0xe7, 0x81, 0x85, 0x5c, 0x70, 0xf0, 0x6c, 0xfc, 0x32, 0xd8, 0x93, 0xd2, 0x74, 0xbc, 0x9a, 0x05,
	0xb6, 0x94, 0x56, 0xf3, 0xcb, 0x59, 0xe0, 0xa0, 0xc7, 0xe0, 0x49, 0x69, 0xb9, 0x1a, 0x5f, 0x5e,
	0x07, 0x03, 0x74, 0x00, 0xee, 0x7c, 0xb1, 0x9a, 0xe1, 0x1f, 0xc6, 0x2f, 0x83, 0xa1, 0x4c, 0x29,
	0xb5, 0x8b, 0x19, 0x0e, 0xf6, 0xd1, 0x3e, 0xd8, 0x2f, 0xe6, 0xaf, 0x03, 0x57, 0xe6, 0xbe, 0xbc,
	0x5a, 0xcc, 0xde, 0x04, 0x5e, 0x32, 0x05, 0x4f, 0xbf, 0x55, 0x8c, 0xa3, 0x6f, 0xc0, 0xd5, 0x4f,
	0x5c, 0x82, 0xf4, 0x43, 0xb6, 0xfb, 0xe4, 0x3d, 0x3d, 0xea, 0x13, 0xae, 0xee, 0x25, 0x7e, 0x74,
	0x6a, 0x9d, 0x1f, 0x83, 0x2b, 0x7f, 0x48, 0x69, 0x3b, 0x77, 0x2f, 0x78, 0x95, 0x7d, 0x5f, 0xac,
	0xef, 0xae, 0xad, 0xb7, 0x43, 0xf5, 0x57, 0x9e, 0xfd, 0x13, 0x00, 0x00, 0xff, 0xff, 0xbc, 0x23,
	0xd0, 0x41, 0x40, 0x07, 0x00, 0x00,
}
